# Generated by Django 4.2.2 on 2023-07-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='ChallengeSuccessRate',
            new_name='ChallengeSucessRate',
        ),
    ]
