name: Testing CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        uses: Gr1N/setup-poetry@v8
      - run: |
          poetry env use python3
          poetry shell
          poetry install
